#!/bin/bash

_PACKAGES=(
  @babel/core
  @babel/eslint-parser
  @babel/preset-env
  babel-loader
  css-loader
  dotenv-webpack
  eslint
  eslint-plugin-import
  html-loader
  html-webpack-plugin
  node-sass
  sass-loader
  style-loader
  stylelint
  stylelint-config-recommended-scss
  stylelint-scss
  webpack
  webpack-cli
  webpack-dev-server
)

rm -rf node_modules yarn.lock

yarn add --dev ${_PACKAGES[@]}

unset _PACKAGES

touch .env
